Repository WhiteyOne/EAC-AIRBNB, pull requests merged in 2025-01, with the labels that each got.

#37 test-feature branch- esme
  00Readme/API-docs-AirBnB.md
Labels: enhancement

#43 Add User logout backend endpoint
  backend/backend/backend/routes/api/index.js
  backend/backend/backend/routes/api/session.js
  backend/backend/backend/routes/api/users.js
  backend/package-lock.json
  backend/package.json
Labels: documentation, help wanted

#42 started phase3
  backend/db/migrations/01-user.js
  backend/db/models/user.js
Labels: bug

#44 Create Github Cheatsheet.md
  Github Cheatsheet.md
Labels: documentation
