Repository WhiteyOne/EAC-AIRBNB, pull requests merged in 2025-02, with the labels that each got.

#47 Phases 0-5 completed
  .DS_Store
  00Readme/API-docs-AirBnB.md
  00Readme/Kanban-cards-AirBnB.md
  README.md
  backend/.env.example
  backend/.sequelizerc
  backend/app.js
  backend/backend/backend/routes/api/index.js
  backend/backend/backend/routes/api/session.js
  backend/backend/backend/routes/api/users.js
  backend/bin/www
  backend/config/index.js
  backend/db/migrations/01-user.js
  backend/db/migrations/02-review-image.js
  backend/db/migrations/03-booking.js
  backend/db/migrations/04-review.js
  backend/db/migrations/05-spots.js
  backend/db/migrations/06-spot-image.js
  backend/db/models/booking.js
  backend/db/models/review.js
  backend/db/models/reviewImage.js
  backend/db/models/spot.js
  backend/db/models/spotImage.js
  backend/db/models/user.js
  backend/db/seeders/01-user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/api/index.js
  backend/routes/api/session.js
  backend/routes/api/users.js
  backend/routes/index.js
  backend/utils/auth.js
  backend/utils/validation.js
Labels: ready

#50 fixed package.json
  backend/package.json
Labels: bug

#55 Scripts to deploy
  package.json
Labels: deployment

#57 Eu/mig model folders
  .DS_Store
  backend/db/migrations/02-review-image.js
  backend/db/migrations/03-booking.js
  backend/db/migrations/04-review.js
  backend/db/migrations/05-spots.js
  backend/db/migrations/06-spot-image.js
  backend/db/models/booking.js
  backend/db/models/review.js
  backend/db/models/reviewImage.js
  backend/db/models/spot.js
  backend/db/models/spotImage.js
Labels: enhancement

#58 moved some migrations/models
  backend/db/migrations/02-spots.js
  backend/db/scratch_migrations/03-spot-image.js
  backend/db/scratch_migrations/04-review.js
  backend/db/scratch_migrations/05-review-image.js
  backend/db/scratch_migrations/06-booking.js
  backend/db/scratch_models/booking.js
  backend/db/scratch_models/review.js
  backend/db/scratch_models/reviewImage.js
  backend/db/scratch_models/spotImage.js
Labels: enhancement

#60 spots model
  backend/db/models/spot.js
Labels: enhancement

#61 Spots added to migrations
  backend/db/migrations/02-spots.js
Labels: development

#63 routes spots and reviews added
  backend/routes/api/index.js
  backend/routes/api/reviews.js
  backend/routes/api/spots.js
Labels: reviews, spots

#64 Users table attributes addition
  backend/db/migrations/01-user.js
  backend/db/models/user.js
Labels: development

#65 Spots seeder and minor edits
  backend/db/migrations/02-spot.js
  backend/db/seeders/01-user.js
  backend/db/seeders/02-spot.js
Labels: development

#66 Spot routes
  backend/db/migrations/02-spot.js
  backend/db/models/spot.js
  backend/db/seeders/02-spot.js
  backend/routes/api/spots.js
Labels: bug, post, route, migrations, spots

#68 Tweaking bugs
  backend/db/migrations/02-spot.js
  backend/db/models/spot.js
  backend/db/seeders/02-spot.js
  backend/routes/api/spots.js
Labels: bug, migrations

#72 Added Reviews Seeder
  backend/db/migrations/04-review.js
  backend/db/models/review.js
  backend/db/scratch_models/review.js
  backend/db/seeders/04-review.js
  backend/routes/api/reviews.js
Labels: reviews, migrations, models, seeders

#73 Migrations, seeds, models
  backend/db/migrations/05-review-image.js
  backend/db/migrations/06-booking.js
  backend/db/models/booking.js
  backend/db/models/review.js
  backend/db/models/reviewImage.js
  backend/db/models/spot.js
  backend/db/models/spotImage.js
  backend/db/models/user.js
  backend/db/seeders/03-spot-images.js
  backend/db/seeders/05-review-images.js
  backend/db/seeders/06-booking.js
  backend/routes/api/spots.js
  backend/routes/api/users.js
Labels: bug, migrations, models, seeders

#75 Added db connection check, fixed description, and fixed userId in spo…
  backend/db/models/index.js
  backend/db/models/spot.js
  backend/routes/api/spots.js
Labels: development

#77 merged all our changes into 1 branch and fixed various issues
  backend/db/models/spotImage.js
  backend/db/seeders/02-spot.js
  backend/routes/api/review-images.js
  backend/routes/api/spots.js
  backend/utils/errorHandler.js
Labels: development

#78 Spots mostly running
  backend/routes/api/index.js
  backend/routes/api/review-images.js
  backend/routes/api/spots.js
Labels: bug, route, spots

#79 Added error handling & bookings routes
  backend/.env.example
  backend/routes/api/bookings.js
  backend/routes/api/index.js
  backend/routes/api/review-images.js
  backend/routes/api/reviews.js
  backend/routes/api/session.js
  backend/routes/api/users.js
Labels: help wanted, route, development

#80 Reviews/ReviewImages routes fix
  backend/routes/api/review-images.js
  backend/routes/api/reviews.js
Labels: development

#83 Getting ready to push to main
  backend/.env.example
  backend/db/seeders/04-review.js
  backend/db/seeders/05-review-images.js
  backend/db/seeders/06-booking.js
  backend/routes/api/bookings.js
  backend/routes/api/index.js
  backend/routes/api/reviews.js
  backend/routes/api/spots.js
Labels: deployment

#87 Fixed Staging
  backend/routes/api/index.js
  backend/routes/api/review-images.js
  backend/routes/api/reviews.js
  backend/routes/api/spots.js
Labels: development

#90 Validations
  backend/db/migrations/02-spot.js
  backend/db/models/booking.js
  backend/db/models/review.js
  backend/db/models/spot.js
  backend/db/models/user.js
  backend/routes/api/users.js
Labels: validations

#91 Fixed 3 spot routes
  backend/package.json
  backend/routes/api/spots.js
  backend/routes/api/users.js
Labels: development

#97 Bookings in Spots fixed
  backend/routes/api/spots.js
Labels: development

#102 Ai/reviews fix 2
  backend/routes/api/reviews.js
Labels: help wanted, route, commenting, reviews

#101 fixed off set
  backend/routes/api/spots.js
Labels: bug

#105 attempting a deployment fix
  backend/db/migrations/02-spot.js
  backend/routes/api/reviews.js
Labels: bug, deployment
